services:
  web:
    env_file:
      - .env
    build: .
    command: >
      sh -c ""
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PYTHONUNBUFFERED=1

  qcluster:
    env_file:
      - .env
    build: .
    command: >
      sh -c "uv run python manage.py wait_for_db &&
        uv run python manage.py qcluster"
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
    depends_on:
      - web
