# Generated by Django 5.2.14 on 2026-05-29 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lesson",
            old_name="lesson_type",
            new_name="status",
        ),
    ]
