# Generated by Django 5.2.14 on 2026-05-29 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="lesson_type",
            field=models.CharField(
                choices=[
                    ("PLANNED", "Planned"),
                    ("FINISHED", "Finished"),
                    ("CANCELED", "Canceled"),
                ],
                default="PLANNED",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="lesson_price",
            field=models.DecimalField(decimal_places=2, default=400, max_digits=10),
        ),
        migrations.AddField(
            model_name="student",
            name="lessons_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="datetime",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="duration",
            field=models.PositiveIntegerField(),
        ),
    ]
