# Generated by Django 5.2.14 on 2026-05-28 17:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_user_is_student_user_is_teacher_user_teacher_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitecode",
            name="code",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
